### PR TITLE
[TPCDS][TEST] Add query output schema check for TPCDS 2.7

### PR DESCRIPTION
**Pull request by turboFei**
### _Why are the changes needed?_

Add query output schema check for TPCDS 2.7

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by ulysses-you** [comment]
Seems we need to make `kyuubi-spark-sql-engine` test `log4j.properties` loglevel to INFO.

Current log length is to large.
```
The job exceeded the maximum log length, and has been terminated.
```

**Comment by turboFei** [comment]
thanks, have adjusted log level

**Comment by turboFei** [comment]
Now GA is slow, close it temporarily.

**Comment by yaooqinn** [comment]
we can tag this test and test it in a separate GA job or even workflow

**Comment by turboFei** [comment]
yes, I also considered using g a tag to include tpcds tests only. will add tpcds2.7 test after it is ready.

**Pull request closed without merging**
