### PR TITLE
[KYUUBI #662]Fix run on k8s

### PR DESCRIPTION
**Pull request by hddong**
### _Why are the changes needed?_

When run on k8s, engine write hostname to zk. But, server can not connect pod by hostname, we should use ip instead.

### _How was this patch tested?_
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @zwangsheng

**Comment by yaooqinn** [comment]
@hddong

Can we control this on the Kyuubi side not based on the cluster manager where engines running against?

We can add a conf directly e.g. `kyuubi.engine.connection.url.use.hostname=true`, then whether underlying platform change or not, we can use this to switch hostname or IP?

**Comment by zwangsheng** [comment]
Hi @hddong , What mode did you submit ？

**Comment by hddong** [comment]
> Hi @hddong , What mode did you submit ？
cluster mode, dirver as a pod.

**Review by yaooqinn — APPROVED** [review]

**Comment by yaooqinn** [comment]
thanks, merged to master for v1.3.0

**Pull request closed without merging**
