### PR TITLE
[KYUUBI #699][DOCS] Add document for kyuubi-extension-spark_3.1 module

### PR DESCRIPTION
**Pull request by ulysses-you**
### _Why are the changes needed?_

Make Kyuubi SQL extension readable.

### _How was this patch tested?_
The screen snapshot is:

image

### CODE REVIEW

**Comment by yaooqinn** [comment]
nit: use extensions or extension

**Review by yaooqinn — APPROVED** [review]

**Comment by ulysses-you** [comment]
cc @yangrong688 this is the late docs.

**Comment by yangrong688** [comment]
> cc @yangrong688 this is the late docs.

I got it, thanks.

**Comment by ulysses-you** [comment]
thanks, merging to master for v1.3.0.

**Pull request closed without merging**
