### PR TITLE
[KYUUBI #551][JDK11] Fix KyuubiSQLExceptionSuite

### PR DESCRIPTION
**Pull request by yaooqinn**
### _Why are the changes needed?_

Make JDK11 work step by step, in this PR, we fix the issue in `KyuubiSQLExceptionSuite` and report a new one in  MetricsSystemSuite

close #559 and file a new ticket to track #689 
### _How was this patch tested?_
- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] [Run test](https://kyuubi.readthedocs.io/en/latest/tools/testing.html#running-tests) locally before make a pull request

### CODE REVIEW

**Comment by yaooqinn** [comment]
cc @jackMintao, can you provide your git `user.name` and `email` for us to give you the credit of the commit? Also cc @pan3793 @ulysses-you

**Comment by pan3793** [comment]
I will fix #689

**Comment by pan3793** [comment]
why travis passed ?

**Comment by pan3793** [comment]
Thanks, merged for v1.3.0.

**Pull request closed without merging**
